<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Aurel Sheremetaj" />

<meta name="date" content="2026-02-11" />

<title>Aurel Sheremetaj Lindjet</title>

<script src="AurelSheremetaj_Sk_lindjet_files/header-attrs-2.20/header-attrs.js"></script>
<script src="AurelSheremetaj_Sk_lindjet_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="AurelSheremetaj_Sk_lindjet_files/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="AurelSheremetaj_Sk_lindjet_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="AurelSheremetaj_Sk_lindjet_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="AurelSheremetaj_Sk_lindjet_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="AurelSheremetaj_Sk_lindjet_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="AurelSheremetaj_Sk_lindjet_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="AurelSheremetaj_Sk_lindjet_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="AurelSheremetaj_Sk_lindjet_files/navigation-1.1/tabsets.js"></script>
<link href="AurelSheremetaj_Sk_lindjet_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="AurelSheremetaj_Sk_lindjet_files/highlightjs-9.12.0/highlight.js"></script>
<link href="AurelSheremetaj_Sk_lindjet_files/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="AurelSheremetaj_Sk_lindjet_files/pagedtable-1.1/js/pagedtable.js"></script>
<script src="AurelSheremetaj_Sk_lindjet_files/kePrint-0.0.1/kePrint.js"></script>
<link href="AurelSheremetaj_Sk_lindjet_files/lightable-0.0.1/lightable.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">



<h1 class="title toc-ignore">Aurel Sheremetaj Lindjet</h1>
<h4 class="author">Aurel Sheremetaj</h4>
<h4 class="date">11 February 2026</h4>

</div>


<div id="hyrje" class="section level1">
<h1>Hyrje</h1>
<p>Qëllimi i këtij studimi është analiza e tendencave dhe lidhjeve mes
tre treguesve kryesorë për ekonominë dhe zhvillimin shoqëror të
Shqipërisë gjatë periudhës 2011–2025, përmes të dhënave tremujore. Të
dhënat përfshijnë: (1) numrin e lindjeve në Shqipëri nga tremujori i
parë i vitit 2011 deri në tremujorin e dytë të vitit 2025, (2) indeksin
tremujor të çmimeve të importit të Shqipërisë nga tremujori i parë i
vitit 2012 deri në tremujorin e dytë të vitit 2025, dhe (3) bilancin
tremujor të energjisë elektrike për eksportet bruto të Shqipërisë për të
njëjtën periudhë. Këto seri kohore përfaqësojnë tre dimensione të
ndryshme të zhvillimit kombëtar – demografik, ekonomik dhe energjetik –
të cilat janë të ndërlidhura në mënyrë sistematike dhe ndikojnë
ndërsjelltë në stabilitetin dhe performancën e vendit.Në datasetin e
parë, treguesi i lindjeve pasqyron ecurinë demografike të vendit, si dhe
ndryshimet strukturore që lidhen me faktorë ekonomikë, emigracionin dhe
politikat sociale. Këto të dhëna do të analizohen për të identifikuar
trendet afatgjata, stinorësinë dhe mundësitë për parashikim të numrit të
lindjeve në të ardhmen. Në datasetin e dytë, analiza fokusohet në
indeksin e çmimeve të importit, i cili është tregues i rëndësishëm i
dinamikës së tregtisë së jashtme dhe i presioneve të inflacionit që
ndikojnë në ekonominë shqiptare. Duke analizuar këtë seri kohore,
synohet të vlerësohen ndryshimet ciklike dhe ndikimet e faktorëve
globalë në çmimet e importit për vendin. Dataseti i tretë përfshin
bilancin tremujor të energjisë elektrike për eksportet bruto, një
tregues kyç për kapacitetin energjetik të Shqipërisë, i cili ndikohet
drejtpërdrejt nga kushtet klimatike, prodhimi hidroenergjetik dhe
kërkesa e tregut rajonal. Ky tregues ndihmon të kuptohet më mirë roli i
sektorit energjetik në ekonominë shqiptare dhe kontributi i tij në
balancën tregtare.Secili prej tre treguesve do të analizohet përmes
metodave statistikore të serive kohore në R Studio, duke përfshirë
vizualizimin, dekompozimin në komponentët trend, sezonë dhe rastësorë,
si dhe ndërtimin e modeleve për parashikim .Parashikimi i saktë i këtyre
treguesve ndihmon në formulimin e politikave afatgjata për zhvillim të
qëndrueshëm, menaxhim të burimeve natyrore dhe planifikim të tregut të
punës. Përmes këtij punimi synohet të krijohet një kuptim
gjithëpërfshirës mbi mënyrën se si ndryshimet në faktorët demografikë,
ekonominë e jashtme dhe energjinë ndikojnë në performancën
makroekonomike të Shqipërisë dhe si mund të përdoren metodat e
statistikës moderne për të parashikuar ecurinë e tyre në të ardhmen.</p>
<hr />
</div>
<div id="paraqitja-grafike" class="section level1">
<h1>Paraqitja grafike</h1>
<pre class="r"><code>library(readxl)

data &lt;- read_excel(&quot;C:\\Users\\35569\\OneDrive\\Documents\\Lindjet 3 mujor.xlsx&quot;)  
head(data)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Koha"],"name":[1],"type":["chr"],"align":["left"]},{"label":["Gjithsej"],"name":[2],"type":["dbl"],"align":["right"]}],"data":[{"1":"2011-1","2":"7425"},{"1":"2011-2","2":"8238"},{"1":"2011-3","2":"9807"},{"1":"2011-4","2":"8815"},{"1":"2012-1","2":"8082"},{"1":"2012-2","2":"8471"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>library(ggplot2)
library(forecast)</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>library(tidyr)</code></pre>
<pre class="r"><code>library(dplyr)
library(tidyr)

data &lt;- data %&gt;%
  separate(Koha, into = c(&quot;Viti&quot;, &quot;Tremujori&quot;), sep = &quot;-&quot;, convert = TRUE)

head(data)</code></pre>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":["Viti"],"name":[1],"type":["int"],"align":["right"]},{"label":["Tremujori"],"name":[2],"type":["int"],"align":["right"]},{"label":["Gjithsej"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"2011","2":"1","3":"7425"},{"1":"2011","2":"2","3":"8238"},{"1":"2011","2":"3","3":"9807"},{"1":"2011","2":"4","3":"8815"},{"1":"2012","2":"1","3":"8082"},{"1":"2012","2":"2","3":"8471"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
<pre class="r"><code>ts_births &lt;- ts(
  data$Gjithsej,
  start = c(min(data$Viti), min(data$Tremujori)),
  frequency = 4
)

ts_births</code></pre>
<pre><code>##       Qtr1  Qtr2  Qtr3  Qtr4
## 2011  7425  8238  9807  8815
## 2012  8082  8471 10257  8663
## 2013  7868  8382 10208  9292
## 2014  8002  8741 10329  8688
## 2015  7646  7991  8715  8363
## 2016  7163  7365  9086  8119
## 2017  6916  7483  8539  7931
## 2018  6657  6745  8213  7319
## 2019  6257  6655  7739  7910
## 2020  6351  6706  8007  7011
## 2021  6301  6319  7680  6911
## 2022  6214  5577  6555  6342
## 2023  5424  5452  6515  6226
## 2024  5428  5380  6483  6019
## 2025  4662  4982</code></pre>
<div id="grafikë" class="section level3">
<h3>Grafikë</h3>
<pre class="r"><code>plot(ts_births,
     type = &quot;o&quot;,              
     col = &quot;darkred&quot;,
     pch = 16,                
     lwd = 2,
     main = &quot;Lindjet – Seri Kohore (tremujor)&quot;,
     ylab = &quot;Numri i lindjeve&quot;,
     xlab = &quot;Koha&quot;)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="sezonalitet" class="section level3">
<h3>sezonalitet</h3>
<pre class="r"><code> #sezonaliteti trendi 
decomp &lt;- decompose(ts_births) 
plot(decomp)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-6-1.png" width="672" />
Nga grafiku i mësipërm shohim se seria e lindjeve karakterizohet nga
sezonalitet i fortë dhe një trend rënës, pjesa e sezonalitetit na tregon
se ka luhatje të rregullta brenda cdo viti ku disa tremujorë kanë
sistematikisht më shumë lindje se të tjerët.Trendi tregon se numri
mesatar i lindjeve ka pësuar ulje graduale gjatë viteve të fundit,
veçanërisht pas vitit 2017, duke reflektuar një prirje negative në
zhvillimin demografik.</p>
<pre class="r"><code>  ggsubseriesplot(ts_births) </code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="grafiku-sezonal" class="section level3">
<h3>Grafiku sezonal</h3>
<pre class="r"><code>library(forecast)
library(ggplot2)

ggsubseriesplot(ts_births, color = &quot;black&quot;) +
  geom_line(aes(group = 1), color = &quot;black&quot;, linewidth = 0.7) +
  geom_hline(aes(yintercept = mean(ts_births)), 
             color = &quot;red&quot;, linetype = &quot;dashed&quot;, linewidth = 0.7) +
  theme_minimal(base_size = 14) +
  labs(
    title = &quot;Subseries Plot për Lindjet&quot;,
    subtitle = &quot;Tregon sezonalitetin brenda secilit tremujor&quot;,
    x = &quot;Tremujori&quot;,
    y = &quot;Numri i lindjeve&quot;
  ) +
  theme(
    plot.title = element_text(face = &quot;bold&quot;, size = 18),
    plot.subtitle = element_text(size = 13),
    strip.text = element_text(size = 14, face = &quot;bold&quot;),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  )</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-8-1.png" width="672" />
Grafiku paraqet lëvizjen e lindjeve brenda çdo tremujori (Q1–Q4) ndër
vite. Vija blu në secilin panel tregon mesataren sezonale të atij
tremujori. Vërehet një model i qartë sezonal: Q3 ka numrin më të lartë
të lindjeve, ndërsa Q1 dhe Q4 kanë nivelet më të ulëta. Kjo tregon se
seria kohore ka sezonalitet të fortë dhe të qëndrueshëm brenda
vitit.</p>
</div>
<div id="kontrolli-i-stacionaritetit" class="section level3">
<h3>Kontrolli i stacionaritetit</h3>
<pre class="r"><code>library(tseries)
adf.test(ts_births)</code></pre>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_births
## Dickey-Fuller = -3.2138, Lag order = 3, p-value = 0.09401
## alternative hypothesis: stationary</code></pre>
<p>Duke bërë kontrollin nëse seria është stacionare ose jo del që vlera
p=0.09401 ku duket që seria jonë është jostacionare</p>
<hr />
</div>
</div>
<div id="sheshimi-ekspoencial" class="section level1">
<h1>Sheshimi ekspoencial</h1>
<p>Në këtë pjesë do të shikojmë zbatimin e sheshimit eksponencial per
serinë tonë nepermjet 3 niveleve te sheshimit eksponencal të
njëfishtë(SES) pa trend, pa sezonalitet, të dyfishtë (Holt) me trend, pa
sezonalitet, të trefishtë (Holt–Winters) me trend dhe sezonalitet</p>
<div id="traintesting" class="section level2">
<h2>Train/testing</h2>
<p>Si fillim do te shikojmë pjesen e trajnimit dhe testimit për serinë
tonë</p>
<pre class="r"><code>h_test &lt;- 8   # 8 tremujorë = 2 vite të fundit
n &lt;- length(ts_births)
cut_point &lt;- time(ts_births)[n - h_test]
ts_train &lt;- window(ts_births, end = cut_point)
ts_test &lt;- window(ts_births, start = cut_point + deltat(ts_births))
ts_train</code></pre>
<pre><code>##       Qtr1  Qtr2  Qtr3  Qtr4
## 2011  7425  8238  9807  8815
## 2012  8082  8471 10257  8663
## 2013  7868  8382 10208  9292
## 2014  8002  8741 10329  8688
## 2015  7646  7991  8715  8363
## 2016  7163  7365  9086  8119
## 2017  6916  7483  8539  7931
## 2018  6657  6745  8213  7319
## 2019  6257  6655  7739  7910
## 2020  6351  6706  8007  7011
## 2021  6301  6319  7680  6911
## 2022  6214  5577  6555  6342
## 2023  5424  5452</code></pre>
<pre class="r"><code>ts_test</code></pre>
<pre><code>##      Qtr1 Qtr2 Qtr3 Qtr4
## 2023           6515 6226
## 2024 5428 5380 6483 6019
## 2025 4662 4982</code></pre>
<p>Seria kohore u nda në train set (2011–2023 Q3) dhe test set (2023
Q4–2025 Q2), duke përdorur 8 tremujorët e fundit si të dhëna testimi.
Kjo lejon vlerësimin e saktë të modeleve duke krahasuar parashikimet me
vlerat reale që nuk janë përdorur në trajnim.</p>
</div>
<div id="sheshimi-eksponencial-i-njëfishtë" class="section level2">
<h2>Sheshimi eksponencial i njëfishtë</h2>
<pre class="r"><code>fit_ses &lt;- ses(ts_train,
               h = h_test,
               initial = &quot;optimal&quot;)

fit_ses</code></pre>
<pre><code>##         Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2023 Q3       6036.354 4899.818 7172.890 4298.172 7774.536
## 2023 Q4       6036.354 4866.865 7205.843 4247.774 7824.933
## 2024 Q1       6036.354 4834.815 7237.893 4198.758 7873.950
## 2024 Q2       6036.354 4803.598 7269.110 4151.016 7921.692
## 2024 Q3       6036.354 4773.152 7299.556 4104.454 7968.254
## 2024 Q4       6036.354 4743.423 7329.285 4058.987 8013.721
## 2025 Q1       6036.354 4714.363 7358.345 4014.543 8058.165
## 2025 Q2       6036.354 4685.927 7386.781 3971.055 8101.653</code></pre>
<p>Për serinë e lindjeve u aplikua modeli i sheshimit eksponencial të
njëfishtë (SES).Duke përdorur të dhënat e trajnimit, SES vlerësoi
parametrin optimal α dhe prodhoi parashikime konstante për 8 tremujorët
e testimit. Të gjitha parashikimet janë rreth vlerës 6036, gjë që tregon
se modeli SES nuk arrin të kapë trendin zbritës që vërehet në seri.</p>
<pre class="r"><code>autoplot(ts_train, series = &quot;Train&quot;, color = &quot;black&quot;) +
  autolayer(fitted(fit_ses), series = &quot;Përshtatja (Fitted)&quot;, color = &quot;blue&quot;) +
  autolayer(ts_test, series = &quot;Reale (Test)&quot;, color = &quot;darkgreen&quot;) +
  autolayer(fit_ses$mean, series = &quot;Parashikimi (SES)&quot;, color = &quot;red&quot;) +
  labs(title = &quot;SES – Përshtatja dhe Parashikimi krahasuar me të dhënat reale&quot;,
       x = &quot;Koha&quot;,
       y = &quot;Numri i lindjeve&quot;) +
  guides(colour = guide_legend(title = &quot;Seria&quot;)) +
  theme_minimal()</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code># Tabela e saktësisë
acc_ses &lt;- accuracy(fit_ses, ts_test)
acc_ses</code></pre>
<pre><code>##                     ME     RMSE      MAE       MPE      MAPE     MASE
## Training set -200.9764 868.9258 722.3179 -3.906778  9.630332 1.780252
## Test set     -324.4790 730.2626 603.2135 -7.132093 11.452682 1.486703
##                    ACF1 Theil&#39;s U
## Training set 0.07199133        NA
## Test set     0.22953432  1.056315</code></pre>
<pre class="r"><code># Kontrolli i mbetjeve
checkresiduals(fit_ses)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from Simple exponential smoothing
## Q* = 125.39, df = 8, p-value &lt; 2.2e-16
## 
## Model df: 0.   Total lags used: 8</code></pre>
<p>Grafiku tregon se modeli SES nuk arrin të përshtatet mirë me serinë e
lindjeve. Edhe pse vlerat e përshtatura (qe ne kete rast eshte vija blu)
e ndjekin serinë në mënyrë të përgjithshme, ato nuk pasqyrojnë dot
sezonalitetin tremujor dhe trendin në rënie. Analiza e mbetjeve tregon
se modeli SES nuk përshtatet mirë me serinë e lindjeve. Mbetjet
paraqesin autokorelacion të fortë dhe nuk sillen si zhurme e bardhe .
Grafiku i ACF dhe histogrami tregojnë se modeli nuk arrin të kapë
trendin dhe sezonalitetin e serisë. Prandaj SES nuk është model i
përshtatshëm për parashikime në këtë rast.</p>
</div>
<div id="sheshimi-eksponenial-i-dyfishte" class="section level2">
<h2>Sheshimi eksponenial i dyfishte</h2>
<pre class="r"><code>fit_holt &lt;- holt(ts_train, h = h_test)
fit_holt</code></pre>
<pre><code>##         Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2023 Q3       6073.549 4978.859 7168.239 4399.365 7747.733
## 2023 Q4       6017.878 4918.617 7117.138 4336.703 7699.052
## 2024 Q1       5962.206 4858.384 7066.029 4274.056 7650.357
## 2024 Q2       5906.535 4798.160 7014.910 4211.422 7601.648
## 2024 Q3       5850.863 4737.945 6963.782 4148.801 7552.926
## 2024 Q4       5795.192 4677.738 6912.646 4086.193 7504.191
## 2025 Q1       5739.521 4617.540 6861.502 4023.599 7455.443
## 2025 Q2       5683.849 4557.350 6810.349 3961.017 7406.682</code></pre>
<p>Tabela paraqet parashikimet e modelit Holt për 8 tremujorët e
ardhshëm. Ky model merr parasysh trendin në rënie të serisë, ndaj vlerat
e parashikuara zbresin gradualisht nga 6073 lindje në 2023 Q3 deri në
rreth 5683 lindje në 2025 Q2.</p>
<pre class="r"><code>autoplot(ts_train, series = &quot;Train&quot;, color = &quot;black&quot;) +
  autolayer(fitted(fit_holt), series = &quot;Përshtatja (Fitted)&quot;, color = &quot;blue&quot;) +
  autolayer(ts_test, series = &quot;Reale (Test)&quot;, color = &quot;darkgreen&quot;) +
  autolayer(fit_holt$mean, series = &quot;Parashikimi (Holt)&quot;, color = &quot;red&quot;) +
  labs(title = &quot;Holt – Përshtatja dhe Parashikimi për serinë e lindjeve&quot;,
       x = &quot;Koha&quot;,
       y = &quot;Numri i lindjeve&quot;) +
  guides(colour = guide_legend(title = &quot;Seria&quot;)) +
  theme_minimal()</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<pre class="r"><code># Saktësia për modelin Holt
acc_holt &lt;- accuracy(fit_holt, ts_test)
acc_holt</code></pre>
<pre><code>##                      ME     RMSE      MAE        MPE      MAPE     MASE
## Training set   32.82308 819.3115 660.8020 -0.8580183  8.570681 1.628638
## Test set     -166.82416 602.5093 543.2036 -4.1551709 10.052108 1.338800
##                   ACF1 Theil&#39;s U
## Training set 0.1236690        NA
## Test set     0.1412184 0.8497919</code></pre>
<pre class="r"><code># Kontrolli i mbetjeve të modelit Holt
checkresiduals(fit_holt)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-14-2.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from Holt&#39;s method
## Q* = 109.29, df = 8, p-value &lt; 2.2e-16
## 
## Model df: 0.   Total lags used: 8</code></pre>
<p>Holt përshtatet mirë me trendin zbritës të lindjeve, por nuk kap
sezonalitetin. Në testim, parashikimet janë afër vlerave reale,
megjithëse më të lëmuara. Modeli projeksionon një vazhdimësi të rënies
së lindjeve në periudhën e ardhshme. Rezultatet e saktësisë tregojnë se
modeli Holt performon dukshëm më mirë se modeli SES. Gabimet RMSE dhe
MAE janë më të ulëta. Holt kap trendin e serisë dhe jep parashikime më
të sakta për të dhënat e testit.</p>
</div>
<div id="sheshimi-eksponencial-i-trefishte" class="section level2">
<h2>Sheshimi eksponencial i trefishte</h2>
<pre class="r"><code># Modeli Holt–Winters me sezonalitet ADDITIV
fit_hw_add &lt;- hw(ts_train, h = h_test, seasonal = &quot;additive&quot;)
fit_hw_add</code></pre>
<pre><code>##         Point Forecast    Lo 80    Hi 80    Lo 95    Hi 95
## 2023 Q3       6950.049 6453.564 7446.535 6190.740 7709.359
## 2023 Q4       6112.699 5576.780 6648.619 5293.081 6932.317
## 2024 Q1       5010.646 4437.970 5583.323 4134.813 5886.480
## 2024 Q2       5264.661 4657.417 5871.905 4335.962 6193.360
## 2024 Q3       6716.802 6076.811 7356.793 5738.020 7695.584
## 2024 Q4       5879.452 5208.297 6550.607 4853.008 6905.896
## 2025 Q1       4777.399 4076.437 5478.361 3705.370 5849.428
## 2025 Q2       5031.414 4301.836 5760.992 3915.621 6147.207</code></pre>
<p>Modeli Holt–Winters me sezonalitet additiv prodhon parashikime që
pasqyrojnë si trendin zbritës, ashtu edhe ndryshimet sezonale të
lindjeve.</p>
<pre class="r"><code>autoplot(ts_train, series = &quot;Train&quot;, color = &quot;black&quot;) +
  autolayer(fitted(fit_hw_add), series = &quot;Përshtatja (Fitted)&quot;, color = &quot;blue&quot;) +
  autolayer(ts_test, series = &quot;Reale (Test)&quot;, color = &quot;darkgreen&quot;) +
  autolayer(fit_hw_add$mean, series = &quot;Parashikimi (HW Additiv)&quot;, color = &quot;red&quot;) +
  labs(title = &quot;Holt–Winters (Additiv) – Përshtatja dhe Parashikimi për lindjet&quot;,
       x = &quot;Koha&quot;,
       y = &quot;Numri i lindjeve&quot;) +
  guides(colour = guide_legend(title = &quot;Seria&quot;)) +
  theme_minimal()</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code># Saktësia dhe diagnostika (Additiv)
acc_hw_add &lt;- accuracy(fit_hw_add, ts_test)
acc_hw_add</code></pre>
<pre><code>##                      ME     RMSE      MAE         MPE     MAPE      MASE
## Training set -22.290150 355.0670 258.4174 -0.44742854 3.374753 0.6369052
## Test set      -6.015325 244.8182 202.4007  0.02747632 3.465276 0.4988444
##                     ACF1 Theil&#39;s U
## Training set  0.05119537        NA
## Test set     -0.04439452 0.2582207</code></pre>
<pre class="r"><code>checkresiduals(fit_hw_add)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-16-2.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from Holt-Winters&#39; additive method
## Q* = 4.6106, df = 8, p-value = 0.7983
## 
## Model df: 0.   Total lags used: 8</code></pre>
<p>Modeli Holt–Winters Additiv jep përshtatjen më të mirë për serinë e
lindjeve. Ai kap trendin në rënie dhe sezonalitetin tremujor.
Parashikimet janë afër vlerave reale të testit, ndërsa mbetjet janë të
rastësishme (p-value 0.79), çka tregon se modeli është i specifikuar
mirë.</p>
<pre class="r"><code>fit_hw_mul &lt;- hw(ts_train, h = h_test, seasonal = &quot;multiplicative&quot;)

# Grafik: Train (real), Fitted, Test (real), Forecast
autoplot(ts_train, series = &quot;Train&quot;, color = &quot;black&quot;) +
  autolayer(fitted(fit_hw_mul), series = &quot;Përshtatja (Fitted)&quot;, color = &quot;blue&quot;) +
  autolayer(ts_test, series = &quot;Reale (Test)&quot;, color = &quot;darkgreen&quot;) +
  autolayer(fit_hw_mul$mean, series = &quot;Parashikimi (HW Multiplikativ)&quot;, color = &quot;red&quot;) +
  labs(title = &quot;Holt–Winters (Multiplikativ) – Përshtatja dhe Parashikimi për lindjet&quot;,
       x = &quot;Koha&quot;,
       y = &quot;Numri i lindjeve&quot;) +
  guides(colour = guide_legend(title = &quot;Seria&quot;)) +
  theme_minimal()</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<pre class="r"><code># Saktësia dhe diagnostika (Multiplikativ)
acc_hw_mul &lt;- accuracy(fit_hw_mul, ts_test)
acc_hw_mul</code></pre>
<pre><code>##                     ME     RMSE      MAE        MPE     MAPE      MASE
## Training set -61.70969 330.5513 226.1272 -0.9299323 3.011819 0.5573217
## Test set     245.44221 314.2722 256.5331  4.1476986 4.385599 0.6322612
##                     ACF1 Theil&#39;s U
## Training set -0.04923861        NA
## Test set     -0.10781498 0.4177405</code></pre>
<pre class="r"><code>checkresiduals(fit_hw_mul)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-17-2.png" width="672" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from Holt-Winters&#39; multiplicative method
## Q* = 2.8099, df = 8, p-value = 0.9457
## 
## Model df: 0.   Total lags used: 8</code></pre>
<p>Modeli multiplikativ pasqyron më saktë sezonalitetin e amplitudës së
ndryshueshme,ka gabime më të ulëta krahasuar me Holt-in klasik dhe SES,
sidomos në periudhën e testimit gjithashtu tregon parashikim të
qëndrueshëm dhe të saktë, me devijim relativ shumë të vogël nga vlerat
reale dhe mbetjet janë të rastësishme dhe pa strukturë.</p>
</div>
<div id="krahasimi-i-saktësisë-së-modeleve" class="section level2">
<h2>Krahasimi i saktësisë së modeleve</h2>
<pre class="r"><code>library(dplyr)
library(tibble)

# Tabela e saktësisë për të gjithë modelet
acc_table &lt;- bind_rows(
  data.frame(Model = &quot;SES&quot;,               accuracy(fit_ses, ts_test)),
  data.frame(Model = &quot;Holt&quot;,              accuracy(fit_holt, ts_test)),
  data.frame(Model = &quot;HW Additive&quot;,       accuracy(fit_hw_add, ts_test)),
  data.frame(Model = &quot;HW Multiplicative&quot;, accuracy(fit_hw_mul, ts_test))
)

# Përzgjedhja e metrikeve më të rëndësishme dhe renditja sipas RMSE
acc_table &lt;- acc_table %&gt;%
  select(Model, RMSE, MAE, MAPE, MASE) %&gt;%
  arrange(RMSE)

knitr::kable(acc_table,
             caption = &quot;Krahasimi i performancës së modeleve të parashikimit për serinë e lindjeve&quot;)</code></pre>
<table>
<caption>Krahasimi i performancës së modeleve të parashikimit për serinë
e lindjeve</caption>
<colgroup>
<col width="23%" />
<col width="24%" />
<col width="12%" />
<col width="12%" />
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr>
<th align="left"></th>
<th align="left">Model</th>
<th align="right">RMSE</th>
<th align="right">MAE</th>
<th align="right">MAPE</th>
<th align="right">MASE</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">Test set…1</td>
<td align="left">HW Additive</td>
<td align="right">244.8182</td>
<td align="right">202.4007</td>
<td align="right">3.465276</td>
<td align="right">0.4988444</td>
</tr>
<tr>
<td align="left">Test set…2</td>
<td align="left">HW Multiplicative</td>
<td align="right">314.2722</td>
<td align="right">256.5331</td>
<td align="right">4.385599</td>
<td align="right">0.6322612</td>
</tr>
<tr>
<td align="left">Training set…3</td>
<td align="left">HW Multiplicative</td>
<td align="right">330.5513</td>
<td align="right">226.1272</td>
<td align="right">3.011819</td>
<td align="right">0.5573217</td>
</tr>
<tr>
<td align="left">Training set…4</td>
<td align="left">HW Additive</td>
<td align="right">355.0670</td>
<td align="right">258.4174</td>
<td align="right">3.374753</td>
<td align="right">0.6369052</td>
</tr>
<tr>
<td align="left">Test set…5</td>
<td align="left">Holt</td>
<td align="right">602.5093</td>
<td align="right">543.2036</td>
<td align="right">10.052108</td>
<td align="right">1.3388002</td>
</tr>
<tr>
<td align="left">Test set…6</td>
<td align="left">SES</td>
<td align="right">730.2626</td>
<td align="right">603.2135</td>
<td align="right">11.452682</td>
<td align="right">1.4867028</td>
</tr>
<tr>
<td align="left">Training set…7</td>
<td align="left">Holt</td>
<td align="right">819.3115</td>
<td align="right">660.8020</td>
<td align="right">8.570681</td>
<td align="right">1.6286375</td>
</tr>
<tr>
<td align="left">Training set…8</td>
<td align="left">SES</td>
<td align="right">868.9258</td>
<td align="right">722.3179</td>
<td align="right">9.630332</td>
<td align="right">1.7802519</td>
</tr>
</tbody>
</table>
<p>Të dhënat tregojnë se Holt–Winters Additiv është modeli më i saktë,
me RMSE dhe MAE më të ulët se modelet e tjera. HW Multiplikativ
performon mirë, por më dobët se versioni additiv. Modelet SES dhe Holt
tregojnë gabime të larta dhe nuk arrijnë të kapin strukturen sezonale të
serisë.</p>
<div id="modeli-më-i-mirë-dhe-parashikimi-2-vjecar"
class="section level3">
<h3>Modeli më i mirë dhe parashikimi 2 vjecar</h3>
<pre class="r"><code>best_model &lt;- acc_table$Model[1]
best_model</code></pre>
<pre><code>## [1] &quot;HW Additive&quot;</code></pre>
<pre class="r"><code>final_fit &lt;- switch(best_model,
                    &quot;SES&quot; = ses(ts_births, h = 8),
                    &quot;Holt&quot; = holt(ts_births, h = 8, damped = FALSE),
                    &quot;HW Additive&quot; = hw(ts_births, h = 8, seasonal = &quot;additive&quot;),
                    &quot;HW Multiplicative&quot; = hw(ts_births, h = 8, seasonal = &quot;multiplicative&quot;),
                    &quot;ETS&quot; = forecast(ets(ts_births), h = 8)
)

autoplot(final_fit) +
  ggtitle(paste0(&quot;Parashikimi 2-vjeçar (8 tremujorë) me modelin: &quot;, best_model)) +
  xlab(&quot;Koha&quot;) +
  ylab(&quot;Numri i lindjeve&quot;) +
  theme_minimal()</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Grafiku i parashikimit 2-vjeçar me modelin Holt-Winters Additiv
tregon që trendi rënës i lindjeve pritet të vazhdojë. Zona blu shfaq
intervalet e besimit (80% dhe 95%), të cilat rriten me kohën, duke
reflektuar pasigurinë natyrore të parashikimeve afatgjata. Modeli kap
mirë sezonalitetin dhe jep një projeksion realist për tremujorët e
ardhshëm.</p>
</div>
<div id="rezultatet-e-parashikimit" class="section level3">
<h3>Rezultatet e parashikimit</h3>
<pre class="r"><code>library(lubridate)</code></pre>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     date, intersect, setdiff, union</code></pre>
<pre class="r"><code>library(tibble)

t &lt;- time(final_fit$mean)

Viti &lt;- floor(t)
Tremujori &lt;- round((t - Viti) * 4 + 1)


Periudha &lt;- paste0(Viti, &quot;-Q&quot;, Tremujori)


final_fc_tbl &lt;- tibble(
  Periudha = Periudha,
  Parashikim = as.numeric(final_fit$mean),
  Lwr95 = as.numeric(final_fit$lower[, &quot;95%&quot;]),
  Upr95 = as.numeric(final_fit$upper[, &quot;95%&quot;])
)

knitr::kable(final_fc_tbl, caption = &quot;Parashikimi 2-vjeçar (8 tremujorë) me intervalet 95%&quot;)</code></pre>
<table>
<caption>Parashikimi 2-vjeçar (8 tremujorë) me intervalet 95%</caption>
<thead>
<tr>
<th align="left">Periudha</th>
<th align="right">Parashikim</th>
<th align="right">Lwr95</th>
<th align="right">Upr95</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">2025-Q3</td>
<td align="right">6129.718</td>
<td align="right">5409.724</td>
<td align="right">6849.711</td>
</tr>
<tr>
<td align="left">2025-Q4</td>
<td align="right">5669.537</td>
<td align="right">4899.959</td>
<td align="right">6439.115</td>
</tr>
<tr>
<td align="left">2026-Q1</td>
<td align="right">4610.412</td>
<td align="right">3794.231</td>
<td align="right">5426.592</td>
</tr>
<tr>
<td align="left">2026-Q2</td>
<td align="right">4693.026</td>
<td align="right">3832.742</td>
<td align="right">5553.311</td>
</tr>
<tr>
<td align="left">2026-Q3</td>
<td align="right">5879.643</td>
<td align="right">4917.324</td>
<td align="right">6841.961</td>
</tr>
<tr>
<td align="left">2026-Q4</td>
<td align="right">5419.462</td>
<td align="right">4419.425</td>
<td align="right">6419.499</td>
</tr>
<tr>
<td align="left">2027-Q1</td>
<td align="right">4360.337</td>
<td align="right">3323.934</td>
<td align="right">5396.739</td>
</tr>
<tr>
<td align="left">2027-Q2</td>
<td align="right">4442.952</td>
<td align="right">3371.398</td>
<td align="right">5514.505</td>
</tr>
</tbody>
</table>
<p>Ky kod gjeneron një tabelë të strukturuar të parashikimit 2-vjeçar,
ku secila vlerë e parashikuar shoqërohet me periudhën përkatëse
(vit–tremujor) dhe intervalet 95% të besueshmërisë. Tabela ofron
informacion të plotë mbi pritshmëritë e modelit dhe pasiguritë e tij,
duke e bërë interpretimin e parashikimeve më të qartë dhe më të
kuptueshëm.</p>
<hr />
</div>
</div>
</div>
<div id="proceset-ma-dhe-ar" class="section level1">
<h1>Proceset MA dhe AR</h1>
<div id="procesi-ma1" class="section level2">
<h2>Procesi MA(1)</h2>
<pre class="r"><code>library(forecast)

set.seed(42)
n &lt;- 100

# Simulimet
ts_ma_pos &lt;- arima.sim(model = list(ma = 0.5), n = n)
ts_ma_neg &lt;- arima.sim(model = list(ma = -0.5), n = n)


par(mfrow = c(1, 2))

# Grafik 1: theta = 0.5
plot(ts_ma_pos,
     type = &quot;l&quot;,
     col = &quot;steelblue&quot;,
     lwd = 2,
     main = expression(paste(&quot;MA(1) me  &quot;, theta[1], &quot; = 0.5&quot;)),
     xlab = &quot;Koha&quot;,
     ylab = &quot;X(t)&quot;)
grid(col = &quot;gray80&quot;)
box(lwd = 1.5)

# Grafik 2: theta = -0.5
plot(ts_ma_neg,
     type = &quot;l&quot;,
     col = &quot;tomato&quot;,
     lwd = 2,
     main = expression(paste(&quot;MA(1) me  &quot;, theta[1], &quot; = -0.5&quot;)),
     xlab = &quot;Koha&quot;,
     ylab = &quot;X(t)&quot;)
grid(col = &quot;gray80&quot;)
box(lwd = 1.5)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code># Rikthen vendosjen e grafikëve në normale
par(mfrow = c(1,1))</code></pre>
<p>Procesi MA(1) me θ₁ = 0.5 paraqet lëvizje më të buta për shkak të
varësisë pozitive, ndërsa me θ₁ = –0.5 jep luhatje më të shpejta dhe
seri më të paqëndrueshme për shkak të varësisë negative mes vlerave.</p>
<pre class="r"><code># Simulimi i një procesi MA(1)
library(forecast)

set.seed(42)
n &lt;- 100
ts_ma1_neg05 &lt;- arima.sim(model = list(ma = 1), n = n)

# Grafik i përmirësuar
plot(ts_ma1_neg05,
     type = &quot;l&quot;,                
     col = &quot;darkorange&quot;,         
     lwd = 2,                   
     main = expression(paste(&quot;Simulimi i procesit MA(1) me  &quot;, theta[1], &quot; = 1&quot;)),
     xlab = &quot;Koha&quot;,
     ylab = &quot;X(t)&quot;)

grid(col = &quot;gray80&quot;)            
box(lwd = 1.5)                  </code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
</div>
<div id="acf-acvf-dhe-pacf-për-proceset-ma1" class="section level2">
<h2>ACF, ACVF, dhe PACF për Proceset MA(1)</h2>
<pre class="r"><code># Simulimi i procesit MA(1) me theta = -0.5
set.seed(42)
ts_ma1_neg05 &lt;- arima.sim(model = list(ma = -0.5), n = 100)

# ACF dhe PACF për procesin MA(1)
par(mfrow = c(1, 2))

acf(ts_ma1_neg05,
    main = expression(paste(&quot;ACF për MA(1) me &quot;, theta[1], &quot; = -0.5&quot;)),
    col = &quot;darkred&quot;,         
    lwd = 2)

pacf(ts_ma1_neg05,
     main = expression(paste(&quot;PACF për MA(1) me &quot;, theta[1], &quot; = -0.5&quot;)),
     col = &quot;darkblue&quot;,       
     lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre class="r"><code># Simulimi i procesit MA(1) me theta = 0.5
set.seed(42)
ts_ma1_neg05 &lt;- arima.sim(model = list(ma = 0.5), n = 100)

# ACF dhe PACF për procesin MA(1)
par(mfrow = c(1, 2))

acf(ts_ma1_neg05,
    main = expression(paste(&quot;ACF për MA(1) me &quot;, theta[1], &quot; = 0.5&quot;)),
    col = &quot;purple&quot;,         
    lwd = 2)

pacf(ts_ma1_neg05,
     main = expression(paste(&quot;PACF për MA(1) me &quot;, theta[1], &quot; = 0.5&quot;)),
     col = &quot;green&quot;,       
     lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre class="r"><code># Simulimi i procesit MA(1) me theta = -1
set.seed(42)
ts_ma1_neg05 &lt;- arima.sim(model = list(ma = 1), n = 100)

# ACF dhe PACF për procesin MA(1)
par(mfrow = c(1, 2))

acf(ts_ma1_neg05,
    main = expression(paste(&quot;ACF për MA(1) me &quot;, theta[1], &quot; = 1&quot;)),
    col = &quot;brown&quot;,        
    lwd = 2)

pacf(ts_ma1_neg05,
     main = expression(paste(&quot;PACF për MA(1) me &quot;, theta[1], &quot; = 1 &quot;)),
     col = &quot;pink&quot;,       
     lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
<div id="ma2" class="section level2">
<h2>MA(2)</h2>
<pre class="r"><code># Koeficientët arbitrarë: theta1 = 0.9, theta2 = -0.3
set.seed(42)
ts_ma2 &lt;- arima.sim(model = list(ma = c(0.9, -0.3)), n = n)

plot(ts_ma2,
     type = &quot;l&quot;,
     col = &quot;darkblue&quot;,   
     lwd = 2,            
     main = expression(paste(&quot;Simulimi i procesit MA(2) me &quot;, 
                             theta[1], &quot;=0.9, &quot;, theta[2], &quot;=-0.3&quot;)),
     ylab = &quot;X(t)&quot;,
     xlab = &quot;Koha&quot;)

grid(col = &quot;lightgray&quot;) </code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 2))

acf(ts_ma2,
    main = &quot;ACF për MA(2)&quot;,
    col = &quot;navy&quot;,     
    lwd = 2)

pacf(ts_ma2,
     main = &quot;PACF për MA(2)&quot;,
     col = &quot;magenta&quot;,   
     lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-27-1.png" width="672" />
## MA(3)</p>
<pre class="r"><code># Koeficientët arbitrarë: thet1=0.5, thet2=0.3, thet3=0.2
ts_ma3 &lt;- arima.sim(model = list(ma = c(0.5, 0.3, 0.2)), n = n)

par(mfrow = c(1, 2))
acf(ts_ma3,
    main = &quot;ACF per MA(3)&quot;,
    col=&quot;darkgreen&quot;,
    lwd=2)
pacf(ts_ma3,
     main = &quot;PACF per MA(3)&quot;,
     col=&quot;gold&quot;,
     lwd=2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<pre class="r"><code># SIMULIMI I PROCESIT MA(35)

set.seed(42)
n &lt;- 200  

# Krijojmë 35 koeficientë MA
ma_params_35 &lt;- c(
  0.6, 0.5, 0.4, 0.3, 0.25, 0.2, 0.15, 0.1,
  rep(0.05, 10),
  rep(0.02, 10),
  rep(0, 7)  # pjesa tjetër zero që plotëson 35 koeficientë
)

# Simulimi
ts_ma35 &lt;- arima.sim(model = list(ma = ma_params_35), n = n)


par(mfrow = c(1, 2), mar = c(4, 4, 4, 1))

acf(ts_ma35,
    main = &quot;ACF për MA(35)&quot;,
    lag.max = 40,
    col = &quot;darkred&quot;,   
    lwd = 2)

pacf(ts_ma35,
     main = &quot;PACF për MA(35)&quot;,
     lag.max = 40,
     col = &quot;darkblue&quot;, 
     lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-29-1.png" width="672" />
Si shembull bëjmë dhe MA(35)</p>
</div>
<div id="ar2" class="section level2">
<h2>AR(2)</h2>
<pre class="r"><code># Simulimi i procesit AR(1) me phi = 0.8
set.seed(42)
n_sim &lt;- 100

ts_ar1_pos08 &lt;- arima.sim(model = list(ar = 0.8), n = n_sim)

plot(ts_ar1_pos08,
     type = &quot;l&quot;,
     col = &quot;darkblue&quot;,   
     lwd = 2,            
     main = expression(paste(&quot;Simulimi i procesit AR(1) me &quot;, phi[1], &quot; = 0.8&quot;)),
     ylab = &quot;X(t)&quot;,
     xlab = &quot;Koha&quot;)

grid(col = &quot;lightgray&quot;) </code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<pre class="r"><code>par(mfrow = c(1, 2))

acf(ts_ar1_pos08,
    main = expression(paste(&quot;ACF për AR(1) me &quot;, phi[1], &quot; = 0.8&quot;)),
    col = &quot;skyblue&quot;,  
    lwd = 2)

pacf(ts_ar1_pos08,
     main = expression(paste(&quot;PACF për AR(1) me &quot;, phi[1], &quot; = 0.8&quot;)),
     col = &quot;purple&quot;,    
     lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-31-1.png" width="672" /></p>
<pre class="r"><code># Simulimi i procesit AR(2)
set.seed(42)
ts_ar2 &lt;- arima.sim(model = list(ar = c(0.6, -0.3)), n = n)

par(mfrow = c(1, 2))

acf(ts_ar2,
    main = &quot;ACF për AR(2)&quot;,
    col = &quot;lightgreen&quot;,    
    lwd = 2)

pacf(ts_ar2,
     main = &quot;PACF për AR(2)&quot;,
     col = &quot;lightblue&quot;,    
     lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<pre class="r"><code># Simulimi i procesit AR(11)
set.seed(42)

phi_ar11 &lt;- c(0.5, -0.2, 0.15, -0.1, 0.08, -0.06, 0.05, -0.04, 0.03, -0.02, 0.01)

ts_ar11 &lt;- arima.sim(model = list(ar = phi_ar11), n = n)

par(mfrow = c(1, 2))

acf(ts_ar11,
    main = &quot;ACF për AR(11)&quot;,
    col = &quot;yellow&quot;,     
    lwd = 2)

pacf(ts_ar11,
     main = &quot;PACF për AR(11)&quot;,
     col = &quot;darkorange&quot;,
     lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-33-1.png" width="672" />
Si shembull kemi bërë dhe AR(11)</p>
</div>
<div id="arma" class="section level2">
<h2>ARMA</h2>
<pre class="r"><code># Koeficientët arbitrarë: phi1=0.7, theta1=0.5
ts_arma11 &lt;- arima.sim(model = list(ar = c(0.7), ma = c(0.5)), n = n)

par(mfrow = c(1, 2))
acf(ts_arma11,
    col=&quot;black&quot;,
    lwd=2,
    main = &quot;ACF per ARMA(1, 1)&quot;)
pacf(ts_arma11,
     main = &quot;PACF per ARMA(1, 1)&quot;,
     col=&quot;gray&quot;,lwd=2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-34-1.png" width="672" />
ACF e modelit ARMA(1,1) zbehet gradualisht, duke treguar ndërthurjen e
komponentëve AR dhe MA. PACF ka vetëm lag-un e parë sinjifikant, ndërsa
të tjerët janë të vegjël, çka është tipike për një proces ARMA(1,1).</p>
<pre class="r"><code>par(mfrow = c(1, 1))</code></pre>
<hr />
</div>
</div>
<div id="analiza-e-serive-kohore-me-modelete-ma-ar-arma"
class="section level1">
<h1>Analiza e serive kohore me modelete MA AR ARMA</h1>
<p>Ndajmë edhe njëherë serin tonë në trajnim/testim per serinë tonë</p>
<pre class="r"><code>h_test &lt;- 8                     # 2 vite test për seri tremujore
n &lt;- length(ts_births)

ts_train &lt;- window(ts_births, end = time(ts_births)[n - h_test])
ts_test  &lt;- window(ts_births, start = time(ts_births)[n - h_test + 1])</code></pre>
<pre class="r"><code>q_order &lt;- 4
# Modelimi MA(2). Diferencimi (d) dhe Autoregresioni (p) vendosen në 0.
model_ma &lt;- arima(ts_train, order = c(0, 0, q_order))</code></pre>
<div id="ndërtimi-i-modelit-ma2" class="section level2">
<h2>Ndërtimi i modelit MA(2)</h2>
<pre class="r"><code># Përcaktojmë rendin q
q_order &lt;- 2

# Modelimi MA(2) mbi të dhënat e trajnimit (ts_train)
model_ma &lt;- arima(ts_train, order = c(0, 0, q_order))

# Afishimi i Modelit MA(2)
cat(&quot;### Përmbledhja e Modelit MA(2) ###\n&quot;)</code></pre>
<pre><code>## ### Përmbledhja e Modelit MA(2) ###</code></pre>
<pre class="r"><code>print(model_ma)</code></pre>
<pre><code>## 
## Call:
## arima(x = ts_train, order = c(0, 0, q_order))
## 
## Coefficients:
##          ma1     ma2  intercept
##       1.1204  0.5422  7670.9540
## s.e.  0.1245  0.1135   303.6274
## 
## sigma^2 estimated as 671657:  log likelihood = -407.11,  aic = 822.22</code></pre>
<pre class="r"><code>print(summary(model_ma))</code></pre>
<pre><code>## 
## Call:
## arima(x = ts_train, order = c(0, 0, q_order))
## 
## Coefficients:
##          ma1     ma2  intercept
##       1.1204  0.5422  7670.9540
## s.e.  0.1245  0.1135   303.6274
## 
## sigma^2 estimated as 671657:  log likelihood = -407.11,  aic = 822.22
## 
## Training set error measures:
##                     ME     RMSE      MAE        MPE     MAPE      MASE
## Training set 0.6767473 819.5467 680.5223 -0.9638114 8.847547 0.7552624
##                     ACF1
## Training set -0.08045017</code></pre>
<pre class="r"><code># Parashikimi për modelin MA(q)
forecast_ma &lt;- forecast(model_ma, h = h_test)


plot(forecast_ma,
     main = paste(&quot;Modeli MA(&quot;, q_order, &quot;): Përshtatja dhe Parashikimi për Lindjet&quot;),
     xlab = &quot;Koha&quot;,
     ylab = &quot;Numri i Lindjeve&quot;,
     xlim = range(time(ts_births)))


lines(fitted(model_ma), col = &quot;blue&quot;)


lines(ts_test, col = &quot;red&quot;, lty = 2)

legend(&quot;topleft&quot;,
       legend = c(&quot;Seria e trajnimit (reale)&quot;,
                  &quot;Seria e përshtatur (MA)&quot;,
                  &quot;Parashikimi (MA)&quot;,
                  &quot;Seria e testimit (reale)&quot;),
       col = c(&quot;black&quot;, &quot;blue&quot;, &quot;blue&quot;, &quot;red&quot;),
       lty = c(1, 1, 2, 2),
       cex = 0.8)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-40-1.png" width="672" />
Modeli MA(2) përshtatet mirë me të dhënat historike, por parashikimet në
periudhën e testimit tregojnë devijime nga vlerat reale.</p>
<pre class="r"><code># Nxjerrim kohet nga ts_test
t_test &lt;- time(ts_test)

# Konvertojmë në formatin Viti–Tremujori
Viti &lt;- floor(t_test)
Tremujori &lt;- round((t_test - Viti) * 4 + 1)
Periudha &lt;- paste0(Viti, &quot;-Q&quot;, Tremujori)

# Ndërtojmë tabelën e krahasimit
rez_ma &lt;- data.frame(
  Periudha = Periudha,
  Parashikimi_MA = as.numeric(forecast_ma$mean),
  Vlera_Reale = as.numeric(ts_test)
)

print(head(rez_ma, 10))</code></pre>
<pre><code>##   Periudha Parashikimi_MA Vlera_Reale
## 1  2023-Q3       6653.211        6515
## 2  2023-Q4       7490.464        6226
## 3  2024-Q1       7670.954        5428
## 4  2024-Q2       7670.954        5380
## 5  2024-Q3       7670.954        6483
## 6  2024-Q4       7670.954        6019
## 7  2025-Q1       7670.954        4662
## 8  2025-Q2       7670.954        4982</code></pre>
<p>Parashikimet e MA(2) janë të afërta në fillim të periudhës së
testimit, por më pas modeli stabilizohet në një vlerë konstante dhe nuk
pasqyron rënien reale të lindjeve, duke treguar kufizime në parashikimet
afatgjata.</p>
</div>
<div id="ndertimi-i-modelit-ar2" class="section level2">
<h2>Ndertimi i modelit AR(2)</h2>
<pre class="r"><code># Përcaktojmë rendin p
p_order &lt;- 2

# Modelimi AR(2) mbi të dhënat e trajnimit (ts_train)
model_ar &lt;- arima(ts_train, order = c(p_order, 0, 0))

# Afishimi i Modelit AR(2)
cat(&quot;### Përmbledhja e Modelit AR(2) ###\n&quot;)</code></pre>
<pre><code>## ### Përmbledhja e Modelit AR(2) ###</code></pre>
<pre class="r"><code>print(model_ar)</code></pre>
<pre><code>## 
## Call:
## arima(x = ts_train, order = c(p_order, 0, 0))
## 
## Coefficients:
##          ar1      ar2  intercept
##       0.7306  -0.1555  7645.1715
## s.e.  0.1395   0.1443   302.6331
## 
## sigma^2 estimated as 847558:  log likelihood = -412.48,  aic = 832.96</code></pre>
<pre class="r"><code>print(summary(model_ar))</code></pre>
<pre><code>## 
## Call:
## arima(x = ts_train, order = c(p_order, 0, 0))
## 
## Coefficients:
##          ar1      ar2  intercept
##       0.7306  -0.1555  7645.1715
## s.e.  0.1395   0.1443   302.6331
## 
## sigma^2 estimated as 847558:  log likelihood = -412.48,  aic = 832.96
## 
## Training set error measures:
##                    ME     RMSE      MAE       MPE     MAPE      MASE      ACF1
## Training set 4.801098 920.6289 756.3603 -1.382462 9.885554 0.8394295 0.1202182</code></pre>
<pre class="r"><code># Parashikimi (Forecast) për periudhën e testimit
forecast_ar &lt;- forecast(model_ar, h = h_test)


plot(forecast_ar,
     main = paste(&quot;Modeli AR(&quot;, p_order, &quot;): Përshtatja dhe Parashikimi për Lindjet&quot;),
     xlab = &quot;Koha&quot;,
     ylab = &quot;Numri i Lindjeve&quot;,
     xlim = range(time(ts_births)))


lines(fitted(model_ar), col = &quot;blue&quot;)


lines(ts_test, col = &quot;red&quot;, lty = 2)

legend(&quot;topleft&quot;,
       legend = c(&quot;Seria e trajnimit (reale)&quot;,
                  &quot;Seria e përshtatur (AR)&quot;,
                  &quot;Parashikimi (AR)&quot;,
                  &quot;Seria e testimit (reale)&quot;),
       col = c(&quot;black&quot;, &quot;blue&quot;, &quot;blue&quot;, &quot;red&quot;),
       lty = c(1, 1, 2, 2),
       cex = 0.8)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-44-1.png" width="672" /></p>
<p>Modeli AR(2) përshtatet mirë me të dhënat historike, por parashikimet
për periudhën e testimit dallojnë ndjeshëm nga vlerat reale. Kjo tregon
se modeli kap strukturën afatshkurtër të serisë, por ka kufizime në
parashikime afatgjata për shkak të variabilitetit të lartë të
lindjeve.</p>
<pre class="r"><code># Koha e ts_test si vite të plotë + tremujor
t_test &lt;- time(ts_test)


Viti &lt;- floor(t_test)
Tremujori &lt;- round((t_test - Viti) * 4 + 1)
Periudha &lt;- paste0(Viti, &quot;-Q&quot;, Tremujori)


rez_ar &lt;- data.frame(
  Periudha = Periudha,
  Parashikimi_AR = as.numeric(forecast_ar$mean),
  Vlera_Reale = as.numeric(ts_test)
)

print(head(rez_ar, 10))</code></pre>
<pre><code>##   Periudha Parashikimi_AR Vlera_Reale
## 1  2023-Q3       6388.134        6515
## 2  2023-Q4       7067.744        6226
## 3  2024-Q1       7418.734        5428
## 4  2024-Q2       7569.509        5380
## 5  2024-Q3       7625.098        6483
## 6  2024-Q4       7642.269        6019
## 7  2025-Q1       7646.172        4662
## 8  2025-Q2       7646.354        4982</code></pre>
<p>Parashikimet AR janë të afërta në fillim të periudhës së testimit,
por më pas modeli mbivlerëson lindjet dhe nuk kap rënien reale të
serisë, duke treguar kufizime në parashikimet afatgjata.</p>
</div>
<div id="gjetja-e-modelit-më-të-përshtatshëm" class="section level2">
<h2>Gjetja e modelit më të përshtatshëm</h2>
<pre class="r"><code># Zgjedhja automatike e modelit AR(p) pa MA dhe pa diferencim
model_ar_auto &lt;- auto.arima(ts_train,
                            max.q = 0,       
                            max.d = 0,       
                            seasonal = FALSE,
                            stepwise = FALSE,
                            ic = &quot;aicc&quot;)

cat(&quot;### Modeli AR(p) më i përshtatshëm i zgjedhur nga auto.arima ###\n&quot;)</code></pre>
<pre><code>## ### Modeli AR(p) më i përshtatshëm i zgjedhur nga auto.arima ###</code></pre>
<pre class="r"><code>print(model_ar_auto)</code></pre>
<pre><code>## Series: ts_train 
## ARIMA(3,0,0) with non-zero mean 
## 
## Coefficients:
##          ar1      ar2     ar3       mean
##       0.8249  -0.6706  0.7727  7430.7528
## s.e.  0.0887   0.1105  0.0874   835.0096
## 
## sigma^2 = 388405:  log likelihood = -392.32
## AIC=794.64   AICc=796   BIC=804.2</code></pre>
<p>Nga rezultai i meëipërm gjejmë se modeli më i përshtatshëm është
AR(3), i cili jep koeficientë të rëndësishëm dhe gabime më të ulëta se
modelet e tjera të testuara.</p>
<pre class="r"><code>cat(&quot;Rendi i zgjedhur (p, d, q):\n&quot;)</code></pre>
<pre><code>## Rendi i zgjedhur (p, d, q):</code></pre>
<pre class="r"><code>print(model_ar_auto)</code></pre>
<pre><code>## Series: ts_train 
## ARIMA(3,0,0) with non-zero mean 
## 
## Coefficients:
##          ar1      ar2     ar3       mean
##       0.8249  -0.6706  0.7727  7430.7528
## s.e.  0.0887   0.1105  0.0874   835.0096
## 
## sigma^2 = 388405:  log likelihood = -392.32
## AIC=794.64   AICc=796   BIC=804.2</code></pre>
<pre class="r"><code># Gjetja e modelit më të përshtatshëm ARIMA/ARMA automatikisht (lejohet d&gt;0 dhe komponente sezonale)


model_arma_auto &lt;- auto.arima(ts_births, 
                           stepwise = FALSE, 
                           approximation = FALSE, 
                           ic = &quot;aicc&quot;) 

cat(&quot;### Modeli ARIMA/ARMA/SARIMA më i Përshtatshëm i zgjedhur nga auto.arima ###\n&quot;)</code></pre>
<pre><code>## ### Modeli ARIMA/ARMA/SARIMA më i Përshtatshëm i zgjedhur nga auto.arima ###</code></pre>
<pre class="r"><code># Parashikimi për periudhën e testimit
forecast_arma_auto &lt;- forecast(model_arma_auto, h = h_test)

# Grafik i serisë së përshtatur dhe parashikimit
plot(forecast_arma_auto,
     main = paste(&quot;Modeli i Zgjedhur ARIMA(&quot;,
                  model_arma_auto$arma[1], &quot;,&quot;,
                  model_arma_auto$arma[6], &quot;,&quot;,
                  model_arma_auto$arma[2], &quot;) - Përshtatja dhe Parashikimi për Lindjet&quot;),
     xlab = &quot;Koha&quot;,
     ylab = &quot;Numri i Lindjeve&quot;,
     xlim = range(time(ts_births)))

# Vlerat e përshtatura (training)
lines(fitted(model_arma_auto), col = &quot;blue&quot;)

# Vlerat reale të testimit
lines(ts_test, col = &quot;red&quot;, lty = 2)

legend(&quot;topleft&quot;,
       legend = c(&quot;Seria e Trajnimit (Reale)&quot;,
                  &quot;Seria e Përshtatur (ARIMA)&quot;,
                  &quot;Parashikimi (ARIMA)&quot;,
                  &quot;Seria e Testimit (Reale)&quot;),
       col = c(&quot;black&quot;, &quot;blue&quot;, &quot;blue&quot;, &quot;red&quot;),
       lty = c(1, 1, 2, 2),
       cex = 0.8)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-50-1.png" width="672" />
Modeli ARIMA(0,0,3) përshtatet shumë mirë me të dhënat historike, por
gjatë periudhës së testimit fillon të mbivlerësojë lindjet dhe nuk kap
rënien e viteve të fundit, duke treguar kufizime në parashikimet
afatgjata.</p>
<pre class="r"><code># Konvertimi i kohës së ts_test në formatin Viti–Tremujori
t_test &lt;- time(ts_test)
Viti &lt;- floor(t_test)
Tremujori &lt;- round((t_test - Viti) * 4 + 1)
Periudha &lt;- paste0(Viti, &quot;-Q&quot;, Tremujori)

# Tabela krahasuese (ARIMA/ARMA)
rez_arma &lt;- data.frame(
  Periudha = Periudha,
  Parashikimi_ARMA = as.numeric(forecast_arma_auto$mean),
  Vlera_Reale = as.numeric(ts_test)
)

print(head(rez_arma, 10))</code></pre>
<pre><code>##   Periudha Parashikimi_ARMA Vlera_Reale
## 1  2023-Q3         5971.522        6515
## 2  2023-Q4         5522.983        6226
## 3  2024-Q1         4721.919        5428
## 4  2024-Q2         4793.961        5380
## 5  2024-Q3         5828.580        6483
## 6  2024-Q4         5393.926        6019
## 7  2025-Q1         4451.914        4662
## 8  2025-Q2         4558.350        4982</code></pre>
<p>Modeli ARMA/ARIMA jep parashikime më të realizta për periudhat e
fundit të testimit dhe reflekton më mirë rënien e lindjeve krahasuar me
modelet e tjera, megjithëse devijime ende ekzistojnë.</p>
<pre class="r"><code>library(dplyr)
library(forecast)
library(knitr)
library(kableExtra)</code></pre>
<pre><code>## 
## Attaching package: &#39;kableExtra&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
<pre class="r"><code># Funksioni për llogaritjen e gabimeve
calculate_errors &lt;- function(actual, predicted) {
  errors &lt;- actual - predicted
  rmse &lt;- sqrt(mean(errors^2, na.rm = TRUE))
  mae  &lt;- mean(abs(errors), na.rm = TRUE)
  mape &lt;- mean(abs(errors / actual), na.rm = TRUE) * 100
  
  data.frame(
    RMSE = rmse,
    MAE  = mae,
    MAPE = mape
  )
}


# Gabimet e Trajnimit
errors_train_ma   &lt;- calculate_errors(ts_train, fitted(model_ma))
errors_train_ar   &lt;- calculate_errors(ts_train, fitted(model_ar))
errors_train_arma &lt;- calculate_errors(ts_train, fitted(model_arma_auto))


# Gabimet e Testimit
errors_test_ma   &lt;- calculate_errors(ts_test, as.numeric(forecast_ma$mean))
errors_test_ar   &lt;- calculate_errors(ts_test, as.numeric(forecast_ar$mean))
errors_test_arma &lt;- calculate_errors(ts_test, as.numeric(forecast_arma_auto$mean))


# Krijimi i tabelës përfundimtare
results_table &lt;- bind_rows(
  
  mutate(errors_train_ma,
         Model = &quot;MA(2)&quot;,
         Seksioni = &quot;Trajnim&quot;),
  
  mutate(errors_test_ma,
         Model = &quot;MA(2)&quot;,
         Seksioni = &quot;Testim&quot;),
  
  mutate(errors_train_ar,
         Model = paste0(&quot;AR(&quot;, model_ar$arma[1], &quot;)&quot;),
         Seksioni = &quot;Trajnim&quot;),
  
  mutate(errors_test_ar,
         Model = paste0(&quot;AR(&quot;, model_ar$arma[1], &quot;)&quot;),
         Seksioni = &quot;Testim&quot;),
  
  mutate(errors_train_arma,
         Model = paste0(&quot;ARIMA(&quot;,
                        model_arma_auto$arma[1], &quot;, &quot;,
                        model_arma_auto$arma[6], &quot;, &quot;,
                        model_arma_auto$arma[2], &quot;)&quot;),
         Seksioni = &quot;Trajnim&quot;),
  
  mutate(errors_test_arma,
         Model = paste0(&quot;ARIMA(&quot;,
                        model_arma_auto$arma[1], &quot;, &quot;,
                        model_arma_auto$arma[6], &quot;, &quot;,
                        model_arma_auto$arma[2], &quot;)&quot;),
         Seksioni = &quot;Testim&quot;)
  
) %&gt;%
  select(Seksioni, Model, RMSE, MAE, MAPE)


# SHFAQJA E TABELËS 
results_table %&gt;%
  knitr::kable(
    caption = &quot;Krahasimi i Metrikave të Gabimit (RMSE, MAE, MAPE)&quot;,
    col.names = c(&quot;Seksioni&quot;, &quot;Modeli&quot;, &quot;RMSE&quot;, &quot;MAE&quot;, &quot;MAPE&quot;),
    digits = c(0, 0, 2, 2, 2),
    booktabs = TRUE,
    align = c(&quot;l&quot;, &quot;l&quot;, &quot;r&quot;, &quot;r&quot;, &quot;r&quot;)
  ) %&gt;%
  kable_styling(
    full_width = FALSE,
    position = &quot;center&quot;
  )</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Krahasimi i Metrikave të Gabimit (RMSE, MAE, MAPE)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Seksioni
</th>
<th style="text-align:left;">
Modeli
</th>
<th style="text-align:right;">
RMSE
</th>
<th style="text-align:right;">
MAE
</th>
<th style="text-align:right;">
MAPE
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Trajnim
</td>
<td style="text-align:left;">
MA(2)
</td>
<td style="text-align:right;">
819.55
</td>
<td style="text-align:right;">
680.52
</td>
<td style="text-align:right;">
8.85
</td>
</tr>
<tr>
<td style="text-align:left;">
Testim
</td>
<td style="text-align:left;">
MA(2)
</td>
<td style="text-align:right;">
2010.03
</td>
<td style="text-align:right;">
1809.30
</td>
<td style="text-align:right;">
33.83
</td>
</tr>
<tr>
<td style="text-align:left;">
Trajnim
</td>
<td style="text-align:left;">
AR(2)
</td>
<td style="text-align:right;">
920.63
</td>
<td style="text-align:right;">
756.36
</td>
<td style="text-align:right;">
9.89
</td>
</tr>
<tr>
<td style="text-align:left;">
Testim
</td>
<td style="text-align:left;">
AR(2)
</td>
<td style="text-align:right;">
1917.85
</td>
<td style="text-align:right;">
1695.34
</td>
<td style="text-align:right;">
31.86
</td>
</tr>
<tr>
<td style="text-align:left;">
Trajnim
</td>
<td style="text-align:left;">
ARIMA(0, 0, 3)
</td>
<td style="text-align:right;">
309.45
</td>
<td style="text-align:right;">
220.16
</td>
<td style="text-align:right;">
2.91
</td>
</tr>
<tr>
<td style="text-align:left;">
Testim
</td>
<td style="text-align:left;">
ARIMA(0, 0, 3)
</td>
<td style="text-align:right;">
578.16
</td>
<td style="text-align:right;">
556.48
</td>
<td style="text-align:right;">
9.63
</td>
</tr>
</tbody>
</table>
<p>ARIMA(0,0,3) ka gabimet më të ulëta në trajnim dhe testim, duke qenë
modeli më i saktë. Modelet MA dhe AR(2) performojnë dobët në testim, me
gabime të larta dhe mungesë aftësie për të kapur rënien reale të
lindjeve.</p>
</div>
</div>
<div id="shtesa" class="section level1">
<h1>Shtesa</h1>
<div id="modeli-nnetar" class="section level2">
<h2>Modeli NNETAR</h2>
<p>Ne kete pjese te studimit jemi marre me shume me modelet linear MA AR
ARIMA por marrim dhe nje model jolinear i quajtur NNETAR (neural network
autoregresiv).Ky model përdor vlerat e kaluara të serisë si input në një
rrjet nervor me një shtresë të fshehtë dhe lejon kapjen e marrëdhënieve
jolineare mes tremujorëve.</p>
<pre class="r"><code>## Modeli NNETAR (Neural Network Autoregresiv)

library(forecast)

set.seed(123)  
model_nnet &lt;- nnetar(ts_train)

cat(&quot;### Përmbledhja e Modelit NNETAR ###\n&quot;)</code></pre>
<pre><code>## ### Përmbledhja e Modelit NNETAR ###</code></pre>
<pre class="r"><code>print(summary(model_nnet))</code></pre>
<pre><code>##           Length Class        Mode     
## x         50     ts           numeric  
## m          1     -none-       numeric  
## p          1     -none-       numeric  
## P          1     -none-       numeric  
## scalex     2     -none-       list     
## size       1     -none-       numeric  
## subset    50     -none-       numeric  
## model     20     nnetarmodels list     
## nnetargs   0     -none-       list     
## fitted    50     ts           numeric  
## residuals 50     ts           numeric  
## lags       4     -none-       numeric  
## series     1     -none-       character
## method     1     -none-       character
## call       2     -none-       call</code></pre>
<pre class="r"><code>forecast_nnet &lt;- forecast(model_nnet, h = h_test)</code></pre>
<p>modeli NNETAR ka ndërtuar një rrjet nervor autoregresiv me 4 vonesa
të serisë dhe një neuron të fshehtë, duke trajnuar 20 versione të
rrjetit për të marrë një parashikim më të qëndrueshëm. Ky model kap
marrëdhënie jolineare që modelet ARIMA nuk i përfshijnë.</p>
<pre class="r"><code>## Grafiku i përshtatjes dhe parashikimit të modelit NNETAR

plot(ts_births,
     xlab = &quot;Koha&quot;,
     ylab = &quot;Numri i Lindjeve&quot;,
     main = &quot;Modeli NNETAR: Përshtatja dhe Parashikimi për Lindjet&quot;,
     col  = &quot;brown&quot;)

lines(fitted(model_nnet), col = &quot;darkgreen&quot;)

lines(forecast_nnet$mean, col = &quot;darkgreen&quot;, lty = 2)

lines(ts_test, col = &quot;darkorange&quot;, lty = 2)

legend(&quot;topleft&quot;,
       bty = &quot;n&quot;,
       lwd = c(1, 1, 1),
       lty = c(1, 1, 2),
       col = c(&quot;brown&quot;, &quot;darkgreen&quot;, &quot;darkorange&quot;),
       legend = c(&quot;Seria reale (e plotë)&quot;,
                  &quot;Seria e përshtatur (NNETAR)&quot;,
                  &quot;Seria e testimit / parashikimi&quot;))</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-54-1.png" width="672" />
Modeli NNETAR përshtatet mirë me të dhënat e trajnimit dhe kap
sezonalitetin e fortë të lindjeve. Në periudhën e testimit, modeli ruan
stabilitetin dhe gjeneron parashikime të arsyeshme, shpesh të afërta me
vlerat reale.</p>
<pre class="r"><code>## Metrikat e gabimit për modelin NNETAR

acc_nnet &lt;- accuracy(forecast_nnet, ts_test)
acc_nnet</code></pre>
<pre><code>##                       ME     RMSE      MAE        MPE     MAPE      MASE
## Training set  -0.9161182 319.0956 255.6365 -0.2182388 3.311502 0.6300514
## Test set     432.0457088 524.2271 441.7106  7.1400320 7.347345 1.0886567
##                    ACF1 Theil&#39;s U
## Training set 0.07923278        NA
## Test set     0.08205630 0.6966388</code></pre>
<p>Metrikat e gabimit tregojnë se modeli NNETAR përshtatet mirë me të
dhënat historike . Në periudhën e testimit gabimet rriten, por
parashikimet mbeten të sakta në përgjithësi. Vlera Theil’s U = 0.69
tregon se modeli parashikon më mirë se një model naiv dhe kap si trendin
ashtu edhe sezonalitetin e serisë.</p>
</div>
<div id="analiza-spektrale" class="section level2">
<h2>Analiza spektrale</h2>
<pre class="r"><code>## Analiza Spektrale e Serisë së Lindjeve: Periodogram + Spektri i Lëmuar

par(mfrow = c(1, 2))

# Periodogrami i thjeshtë
spec.pgram(ts_births,
           log = &quot;no&quot;,
           main = &quot;Periodogrami i Serisë së Lindjeve&quot;,
           xlab = &quot;Frekuenca&quot;,
           ylab = &quot;Densiteti Spektral&quot;,
           col = &quot;darkblue&quot;)

# Spectral density e lëmuar
spec.pgram(ts_births,
           spans = c(5, 5),
           log = &quot;no&quot;,
           main = &quot;Densiteti Spektral i Lëmuar&quot;,
           xlab = &quot;Frekuenca&quot;,
           ylab = &quot;Densiteti Spektral&quot;,
           col = &quot;red&quot;)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>Analiza spektrale tregon një kulm shumë të qartë rreth frekuencës
0.25, e cila korrespondon me një periudhë prej 4 tremujorësh. Kjo
konfirmon praninë e një sezonaliteti vjetor të fortë në serinë e
lindjeve. Spektri i lëmuar thekson akoma më qartë këtë frekuencë
dominuese, duke treguar se cikli sezonal është ritmik dhe i qëndrueshëm
gjatë viteve.</p>
</div>
<div id="krahasimi-i-modeleve" class="section level2">
<h2>Krahasimi i modeleve</h2>
<pre class="r"><code>library(ggplot2)
library(forecast)


fc_ma &lt;- forecast(model_ma, h = h_test)
fc_ar &lt;- forecast(model_ar, h = h_test)
fc_arima &lt;- forecast(model_ar_auto, h = h_test)
fc_nnet &lt;- forecast(model_nnet, h = h_test)

df_compare &lt;- data.frame(
  Koha = time(ts_test),
  Reale = as.numeric(ts_test),
  MA = as.numeric(fc_ma$mean),
  AR = as.numeric(fc_ar$mean),
  ARIMA = as.numeric(fc_arima$mean),
  NNETAR = as.numeric(fc_nnet$mean)
)

ggplot(df_compare, aes(x = Koha)) +
  geom_line(aes(y = Reale, color = &quot;Reale&quot;), size = 1.2) +
  geom_line(aes(y = MA, color = &quot;MA(2)&quot;)) +
  geom_line(aes(y = AR, color = &quot;AR(2)&quot;)) +
  geom_line(aes(y = ARIMA, color = &quot;ARIMA&quot;)) +
  geom_line(aes(y = NNETAR, color = &quot;NNETAR&quot;), linetype = &quot;dashed&quot;, size = 1.1) +
  scale_color_manual(values = c(
    &quot;Reale&quot; = &quot;black&quot;,
    &quot;MA(2)&quot; = &quot;brown&quot;,
    &quot;AR(2)&quot; = &quot;orange&quot;,
    &quot;ARIMA&quot; = &quot;blue&quot;,
    &quot;NNETAR&quot; = &quot;purple&quot;
  )) +
  ggtitle(&quot;Krahasimi i Parashikimeve midis Modeleve&quot;) +
  xlab(&quot;Koha&quot;) + ylab(&quot;Numri i Lindjeve&quot;) +
  theme_minimal(base_size = 14) +
  theme(legend.title = element_blank())</code></pre>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was
## generated.</code></pre>
<pre><code>## Don&#39;t know how to automatically pick scale for object of type &lt;ts&gt;. Defaulting
## to continuous.</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
</div>
<div id="stabiliteti-i-modeleve-në-kohë" class="section level2">
<h2>Stabiliteti i modeleve në kohë</h2>
<pre class="r"><code>rolling_rmse &lt;- function(ts_data, model_type = c(&quot;MA&quot;, &quot;AR&quot;, &quot;ARIMA&quot;),
                         window = 40) {
  
  model_type &lt;- match.arg(model_type)
  n &lt;- length(ts_data)
  rmse_values &lt;- numeric(n - window)
  
  for (i in seq_len(n - window)) {
    
    train &lt;- ts_data[i:(i + window - 1)]
    test  &lt;- ts_data[i + window]
    
    if (model_type == &quot;MA&quot;) {
      fit &lt;- Arima(train, order = c(0, 0, 2))
    }
    
    if (model_type == &quot;AR&quot;) {
      fit &lt;- Arima(train, order = c(model_ar$arma[1], 0, 0))
    }
    
    if (model_type == &quot;ARIMA&quot;) {
      fit &lt;- auto.arima(train, seasonal = FALSE)
    }
    
    forecast_val &lt;- forecast(fit, h = 1)$mean
    rmse_values[i] &lt;- sqrt((test - forecast_val)^2)
  }
  
  return(rmse_values)
}


rmse_ma_roll    &lt;- rolling_rmse(ts_train, &quot;MA&quot;)
rmse_ar_roll    &lt;- rolling_rmse(ts_train, &quot;AR&quot;)
rmse_arima_roll &lt;- rolling_rmse(ts_train, &quot;ARIMA&quot;)


plot(rmse_ma_roll, type = &quot;l&quot;, col = &quot;blue&quot;, lwd = 2,
     main = &quot;Rolling RMSE – Stabiliteti i Modeleve&quot;,
     xlab = &quot;Dritarja Kohore&quot;, ylab = &quot;RMSE&quot;)

lines(rmse_ar_roll, col = &quot;red&quot;, lwd = 2)
lines(rmse_arima_roll, col = &quot;darkgreen&quot;, lwd = 2)

legend(&quot;topright&quot;,
       legend = c(&quot;MA&quot;, &quot;AR&quot;, &quot;ARIMA&quot;),
       col = c(&quot;blue&quot;, &quot;red&quot;, &quot;darkgreen&quot;),
       lwd = 2)</code></pre>
<p><img src="AurelSheremetaj_Sk_lindjet_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>Nga grafiku vërehet se modelet MA dhe AR shfaqin variabilitet të
konsiderueshëm të RMSE-së në dritare të ndryshme kohore, duke treguar
ndjeshmëri të lartë ndaj përzgjedhjes së mostrës së trajnimit dhe
ndryshimeve në strukturën e serisë.Në kontrast, modeli ARIMA paraqet një
sjellje më të qëndrueshme, me luhatje më të moderuara të gabimit dhe me
vlera përgjithësisht më të ulëta të RMSE-së gjatë gjithë periudhës së
vlerësimit.</p>
</div>
<div id="krahasimi-statistik-i-parashikimeve" class="section level2">
<h2>Krahasimi statistik i parashikimeve</h2>
<pre class="r"><code># Gabimet 1-hap përpara
errors_ma &lt;- ts_test - as.numeric(forecast_ma$mean)
errors_ar &lt;- ts_test - as.numeric(forecast_ar$mean)
errors_arima &lt;- ts_test - as.numeric(forecast_arma_auto$mean)

# Heqim NA nëse ekzistojnë
errors_ma &lt;- na.omit(errors_ma)
errors_ar &lt;- na.omit(errors_ar)
errors_arima &lt;- na.omit(errors_arima)

# MA vs AR
dm_ma_ar &lt;- dm.test(
  errors_ma,
  errors_ar,
  h = 1,
  power = 2
)

# AR vs ARIMA
dm_ar_arima &lt;- dm.test(
  errors_ar,
  errors_arima,
  h = 1,
  power = 2
)

# MA vs ARIMA
dm_ma_arima &lt;- dm.test(
  errors_ma,
  errors_arima,
  h = 1,
  power = 2
)

dm_ma_ar</code></pre>
<pre><code>## 
##  Diebold-Mariano Test
## 
## data:  errors_maerrors_ar
## DM = 2.5264, Forecast horizon = 1, Loss function power = 2, p-value =
## 0.03944
## alternative hypothesis: two.sided</code></pre>
<pre class="r"><code>dm_ar_arima</code></pre>
<pre><code>## 
##  Diebold-Mariano Test
## 
## data:  errors_arerrors_arima
## DM = 2.8955, Forecast horizon = 1, Loss function power = 2, p-value =
## 0.02313
## alternative hypothesis: two.sided</code></pre>
<pre class="r"><code>dm_ma_arima</code></pre>
<pre><code>## 
##  Diebold-Mariano Test
## 
## data:  errors_maerrors_arima
## DM = 3.2381, Forecast horizon = 1, Loss function power = 2, p-value =
## 0.01429
## alternative hypothesis: two.sided</code></pre>
<pre class="r"><code>dm_results &lt;- data.frame(
  Krahasimi = c(&quot;MA vs AR&quot;, &quot;AR vs ARIMA&quot;, &quot;MA vs ARIMA&quot;),
  Statistik_DM = c(
    dm_ma_ar$statistic,
    dm_ar_arima$statistic,
    dm_ma_arima$statistic
  ),
  p_value = c(
    dm_ma_ar$p.value,
    dm_ar_arima$p.value,
    dm_ma_arima$p.value
  )
)

dm_results %&gt;%
  knitr::kable(
    caption = &quot;Rezultatet e Testit Diebold–Mariano&quot;,
    digits = c(0, 3, 4),
    booktabs = TRUE,
    col.names = c(&quot;Krahasimi&quot;, &quot;Statistika DM&quot;, &quot;p-value&quot;),
    align = c(&quot;l&quot;, &quot;r&quot;, &quot;r&quot;)
  ) %&gt;%
  kable_styling(
    full_width = FALSE,
    position = &quot;center&quot;
  )</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Rezultatet e Testit Diebold–Mariano
</caption>
<thead>
<tr>
<th style="text-align:left;">
Krahasimi
</th>
<th style="text-align:right;">
Statistika DM
</th>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
MA vs AR
</td>
<td style="text-align:right;">
2.526
</td>
<td style="text-align:right;">
0.0394
</td>
</tr>
<tr>
<td style="text-align:left;">
AR vs ARIMA
</td>
<td style="text-align:right;">
2.896
</td>
<td style="text-align:right;">
0.0231
</td>
</tr>
<tr>
<td style="text-align:left;">
MA vs ARIMA
</td>
<td style="text-align:right;">
3.238
</td>
<td style="text-align:right;">
0.0143
</td>
</tr>
</tbody>
</table>
<p>Të tre testet Diebold–Mariano rezultojnë statistikisht të rëndësishme
(p &lt; 0.05), duke treguar se modeli ARIMA ofron parashikime më të
sakta krahasuar me modelet MA dhe AR.</p>
</div>
</div>
<div id="përfundime" class="section level1">
<h1>Përfundime</h1>
<p>Gjatë analizimit të kësaj serie kohore u konstatua se lindjet në
Shqipëri shfaqin një trend të qartë rënës, i shoqëruar me komponentë
sezonalë të përsëritur, ku disa tremujorë paraqesin nivele më të ulëta
lindjesh çdo vit. Këto karakteristika tregojnë se seria nuk është
thjesht stacionare, por ndikohet nga faktorë strukturorë afatgjatë dhe
luhatje periodike. Nga modelet e ndërtuara dhe të vlerësuara, modeli
SARIMA rezulton më i përshtatshmi për përshkrimin e sjelljes së serisë,
pasi arrin të kapë njëkohësisht trendin rënës dhe sezonalitetin e
pranishëm në të dhëna. Analiza e stabilitetit përmes metodës së rolling
RMSE tregon se ky model ofron performancë më të qëndrueshme në kohë,
duke ruajtur gabime më të ulëta dhe më pak të luhatshme krahasuar me
modelet alternative. Modeli NNETAR shfaq aftësi të mira në kapjen e
lëvizjeve jolineare dhe të ndryshimeve afatshkurtra në seri, duke
ndjekur dridhjet lokale të të dhënave. Modeli ARIMA(0,0,3) rezulton
relativisht i qëndrueshëm në trajnime, por në periudhën e testimit
tenton të mbivlerësojë lindjet, duke u shkëputur nga vlerat reale në
fund të horizontit parashikues. Nga ana tjetër, modeli AR(2) kap më mirë
strukturën dinamike të serisë, por nuk arrin të përfshijë në mënyrë të
qartë komponentën sezonalë, ndërsa modeli MA(2) fokusohet kryesisht në
lëvizjet afatshkurtra. Në tërësi, rezultatet e këtij studimi sugjerojnë
se rënia e lindjeve në Shqipëri është një fenomen i vazhdueshëm, i cili
pritet të thellohet edhe më tej në vitet në vijim.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
